### ISSUE TITLE
Global initialization problem.

### ISSUE THREAD

**Issue by wise-sir-bedevere** [RedhawkSDR/VITA49Libraries#3]
The Source and Sink VITA49 components on Fedora 24 crash when dragged out to the chalkboard. Tracking this down, it appears to be an issue with the ordering of initialization of some the global variables in libVITA49. The global variables in Timestamp.cc are being initialized before the ones in VRTConfig.cc, but the variables in Timestamp.cc are dependent on the ones in VRTConfig.cc being initialized in order to properly construct themselves.

**Comment by jkb-axios** [comment]
fixed
